# Generated by Django 4.2.3 on 2023-07-14 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('security', 'Security'), ('waste', 'Waste'), ('electricity', 'Electricity'), ('others', 'Others')], default='security', max_length=15)),
                ('tx_ref', models.CharField(max_length=200, unique=True)),
                ('tx_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
